version: "2.3"

volumes:
  db-data-back-g2:
    external: true

services:
  db-back-g2:
    container_name: db-back-g2
    image: postgres:alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=backend
    volumes:
      - db-data-back-g2:/var/lib/postgresql/data

    # environment:
    #   - POSTGRES_USER=$POSTGRES_USER
    #   - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    #   - POSTGRES_DB=$POSTGRES_DB